language: node_js

node_js:
  - "10"

notifications:
  slack: jhonatanmedeiros:Qao51y7bLNTtBgO6ytrC7tXb

cache:
  yarn: true
  directories:
    - node_modules

addons:
  chrome: stable

env:
  - CI=true

script:
  - npm run lint
  - npm run e2e
  - npm run build:prod

before_deploy:
  - npm install netlify-cli -g

deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE_ID --auth $NETLIFY_PUBLISH_KEY -p --dir ./dist/bank-account-front
  skip_cleanup: true
  on:
    branch: master
